name: Run Python
on:
    push:
jobs:
    build:
        name: set and run
        runs-on: ubuntu-lastest
        steps:
            - uses: actions/checkout@v2
            - name: step1
              run: |
                python3 main.py